name: Return Dispatch
description: Dispatch an action and return the new run ID.
author: Alex Miller
branding:
  icon: refresh-cw
  color: green
outputs:
  run_id:
    description: The identified Run ID.
inputs:
  token:
    description: GitHub Personal Access Token for making API requests.
    required: true
  ref:
    description: The git reference for the workflow. The reference can be a branch or tag name.
  repo:
    description: Repository of the action to dispatch.
    required: true
  owner:
    description: Owner of the given repository.
    required: true
  workflow:
    description: Workflow to return an ID for. Can be the ID or the workflow filename.
    required: true
  workflow_trigger:
    description: Event triggering the workflow. Can be workflow_dispatch or repository_dispatch.
    default: workflow_dispatch
  workflow_inputs:
    description: A flat JSON object, only supports strings, numbers, and booleans (as per workflow inputs API).
  event_type:
    description: Event type in case the workflow trigger is a repository_dispatch.
  client_payload:
    description: Client payload in case the workflow trigger is a repository_dispatch.
  workflow_timeout_seconds:
    description: Time until giving up waiting for the start of the workflow run.
    default: 300

runs:
  using: node20
  main: dist/index.js
